In [ ]:
# Import library
import numpy as np
from numpy import pi

In [ ]:
import csv
with open('/content/iris.data', 'r') as fd:
  reader = csv.reader(fd)
  result = []
  for row in reader:
    if isinstance(row, list) and len(row) == 5:
      current_row = [float(row[0]), float(row[1]), float(row[2]), float(row[3]), str(row[4])]
      result.append(current_row)
print(result)

[[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'], [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'], [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'], [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'], [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'], [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'], [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'], [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'], [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'], [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'], [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'], [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'], [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'], [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'], [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'], [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'], [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'], [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'], [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'], [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'], [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'], [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'], [4.6, 3.6, 1.0, 0.2, 'Iris-setosa'], [5.1, 3.3, 1.7, 0.5, 'Iris-setosa'], [4.8, 3.4, 1.9, 0.2, 'Iris-setosa'], [5.0, 3.0, 1.6, 0.2, 'Iris-setosa'], [5.0, 3.4, 1.6, 0.4, 'Iris-setosa'], 

Find the target in the dataset and see the column in the dataset (see the index):

In [ ]:
npa = np.delete(result, 4, 1)
print(npa)

[['5.1' '3.5' '1.4' '0.2']
 ['4.9' '3.0' '1.4' '0.2']
 ['4.7' '3.2' '1.3' '0.2']
 ['4.6' '3.1' '1.5' '0.2']
 ['5.0' '3.6' '1.4' '0.2']
 ['5.4' '3.9' '1.7' '0.4']
 ['4.6' '3.4' '1.4' '0.3']
 ['5.0' '3.4' '1.5' '0.2']
 ['4.4' '2.9' '1.4' '0.2']
 ['4.9' '3.1' '1.5' '0.1']
 ['5.4' '3.7' '1.5' '0.2']
 ['4.8' '3.4' '1.6' '0.2']
 ['4.8' '3.0' '1.4' '0.1']
 ['4.3' '3.0' '1.1' '0.1']
 ['5.8' '4.0' '1.2' '0.2']
 ['5.7' '4.4' '1.5' '0.4']
 ['5.4' '3.9' '1.3' '0.4']
 ['5.1' '3.5' '1.4' '0.3']
 ['5.7' '3.8' '1.7' '0.3']
 ['5.1' '3.8' '1.5' '0.3']
 ['5.4' '3.4' '1.7' '0.2']
 ['5.1' '3.7' '1.5' '0.4']
 ['4.6' '3.6' '1.0' '0.2']
 ['5.1' '3.3' '1.7' '0.5']
 ['4.8' '3.4' '1.9' '0.2']
 ['5.0' '3.0' '1.6' '0.2']
 ['5.0' '3.4' '1.6' '0.4']
 ['5.2' '3.5' '1.5' '0.2']
 ['5.2' '3.4' '1.4' '0.2']
 ['4.7' '3.2' '1.6' '0.2']
 ['4.8' '3.1' '1.6' '0.2']
 ['5.4' '3.4' '1.5' '0.4']
 ['5.2' '4.1' '1.5' '0.1']
 ['5.5' '4.2' '1.4' '0.2']
 ['4.9' '3.1' '1.5' '0.1']
 ['5.0' '3.2' '1.2' '0.2']
 ['5.5' '3.5' '1.3' '0.2']
 

In [ ]:
npa = npa.astype(float)

Check mean, median, standard deviation for 1st column:

In [ ]:
mean = np.mean(npa, axis=0)
mean_0 = mean[0]
print(mean_0)

5.843333333333335


In [ ]:
median = np.median(npa, axis=0)
median_0 = median[0]
print(median_0)

5.8


In [ ]:
std = np.std(npa, axis=0)
std_0 = std[0]
print(std_0)

0.8253012917851409


Insert the 20th value of np.nan at the typographic positions in the array (if the randomness is different, the positions may overlap, so you know the solution, as it guarantees 20 unique positions):

In [ ]:
#Task: Insert 20 values of np.nan at random positions in the array.
#Solution: In the mind, we transform a 2D array into a 1D one. 
#Let's generate 20 random numbers from 1 to 600 (the number of elements of a 1D array is 4*150 = 600). 
#Now let's find the position of the generated number in the 2D array. 
#To find an element along the X-axis, we use modulo division, along the Y-axis - integer division. 
#Finally, let's write the np.nan to the array according to the obtained coordinates.
r_range = np.random.choice(np.arange(1, len(npa.ravel()) + 1), 20, replace=False) #generate random number [1; 600]
r_npa = np.copy(npa)
for r_number in r_range:
  npa_x = npa.shape[1]
  r_x = r_number % npa_x
  r_x = r_x if r_x != 0 else npa_x #unique situation: for modulo division for the last element in a row
  r_y = r_number // npa_x + 1
  #print([r_x - 1, r_y - 1])
  r_npa[r_y - 1][r_x - 1] = np.nan #subtract 1 from the coordinates to write to the array
print(r_npa)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 nan]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 nan 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 nan 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 nan]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 nan 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [nan 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Find positions of inserted np.nan values ​​in 1st column:

In [ ]:
#Task: Find positions of inserted np.nan values in 1st column
npa_fc = np.copy(r_npa) #fc - first column
npa_fc = np.delete(npa_fc, np.s_[1:4], axis=1) #delete columns [1:3], only column 0 remains
where_nan = np.where(np.isnan(npa_fc)) #where_nan[0] - contains Y-axis coordinates. where_nan[1] - contains X-axis coordinates.
zip_nan = list(zip(where_nan[0], where_nan[1]))
print(zip_nan)

[(43, 0), (123, 0), (130, 0), (137, 0)]


Filter array after mind: values ​​in 3rd column > 1.5 and values ​​in 1st column < 5.0:

In [ ]:
rf_npa = r_npa[((r_npa[:,2] > 1.5) & (r_npa[:, 0] < 5.0))] #rf - random, filtered
print(rf_npa)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Change all values ​​of np.nan to 0:


In [ ]:
wn_r_npa = np.copy(rf_npa) #wn - without nan
wn_r_npa[np.isnan(wn_r_npa)] = 0
print(wn_r_npa)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Count all unique values ​​in the array and display them all at once from the kilkish:

In [ ]:
values, counts = np.unique(wn_r_npa, return_counts=True)
print(values, counts)

[0.2 1.  1.6 1.7 1.9 2.4 2.5 3.1 3.2 3.3 3.4 4.5 4.7 4.8 4.9] [4 1 3 1 1 1 1 1 1 1 2 1 1 3 2]


Divide the array horizontally into 2 equal parts (don't beat absolute numbers, make two arrays of 4 columns each):

In [ ]:
d_wn_r_npa1, d_wn_r_npa2 = np.split(wn_r_npa, 2) #d - divided
print(d_wn_r_npa1)
print(d_wn_r_npa2)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]]
[[4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Sort arrays by 1st column: 1st for increase, 2nd for change:


In [ ]:
#Task: Sort both arrays by the 1st column: 1st by increasing, 2nd by decreasing
sorted_npa1 = d_wn_r_npa1[d_wn_r_npa1[:, 0].argsort()]
sorted_npa2 = d_wn_r_npa2[d_wn_r_npa2[:, 0].argsort()[::-1]]
print(sorted_npa1)
print(sorted_npa2)

[[4.7 3.2 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]]
[[4.9 2.5 4.5 1.7]
 [4.9 2.4 3.3 1. ]
 [4.8 3.1 1.6 0.2]]


Collect insults arrays in one target:

In [ ]:
conc_npa = np.concatenate((sorted_npa1, sorted_npa2))
print(conc_npa)

[[4.7 3.2 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.9 2.5 4.5 1.7]
 [4.9 2.4 3.3 1. ]
 [4.8 3.1 1.6 0.2]]


Find the most frequently repeated value in an array:

In [ ]:
#Task: Find the most frequently repeated value in an array
values, counts = np.unique(conc_npa, return_counts=True)
max_values = values[counts == counts.max()]
print(max_values)

[0.2]


Write a function so that it multiplies all the values ​​in the column, if it is less than the average value in the column, by 2, or divides the other values ​​by 4. Freeze the removed function up to the 3rd column:


In [ ]:
#Task: Write a function that would multiply all values in a column that are less than the average value in that column by 2, and divide the other values by 4.
#Task: Apply the obtained function to the 3rd column
def update_array_by_column(a, column):
  c_num = column - 1
  new_a = np.copy(a)
  mean = np.mean(a, axis = 0)
  print("Mean column value:", mean[c_num])
  new_a[:, c_num] = np.where(a[:, c_num] < mean[c_num], a[:, c_num]*2, a[:, c_num]/4)
  return new_a
result = update_array_by_column(conc_npa, 3)
print(result)

Mean column value: 2.4166666666666665
[[4.7   3.2   3.2   0.2  ]
 [4.8   3.4   3.2   0.2  ]
 [4.8   3.4   3.8   0.2  ]
 [4.9   2.5   1.125 1.7  ]
 [4.9   2.4   0.825 1.   ]
 [4.8   3.1   3.2   0.2  ]]
